### ISSUE TITLE
Adding nodes coded in Faust?

### ISSUE THREAD

**Issue by sletz** [chaosprint/glicol#25]
You may be interested to use [Faust](https://faust.grame.fr) to add new nodes in the system. Faust can generate Rust code.

**Comment by jarmitage** [comment]
@sletz is there a canonical approach for this? Is this the closest? https://github.com/Frando/rust-faust

**Comment by sletz** [comment]
Yes AFAICS.

**Comment by chaosprint** [comment]
Hi @sletz first thank you so much for opening the issue. It took me a long time to write this up but I have been thinking about this issue all the time.

I think my main concern is the conflicts between license as I don't have any plan to change the MIT license in this repo so far, as it is widely accepted in the Rust community.

The other concern for me is about the ergonomics and the complexity management. As you may have noticed in the past months, Glicol has been shaped for beginners to get started with audio programming. Thus, to have clear Rust code examples would be very beneficial for them. The plan for future is to write as many audio effects on demands manually all in Rust, which can be easier for me or contributors to debug and manage. And I guess that would be the meaning of using Rust for audio as it is essentially a different style for implementing audio.

I have tried to download the exported Rust code from the online IDE. Some thoughts:
- perhaps it's better to generate a `lib` rather than a `bin` and provide the `main` func in the `examples`.
- there are some boilerplate code that makes the generated code really long; perhaps use macros?
- yet the readability still has some room for improvement; here another problem is that if too many macros are involved, it would further harm the readability

In general, I think the code generation is a cool idea and it's great to see that it has been used in many different projects such as this one (https://github.com/kofigumbs/typebeat). Yet given the reasons I mentioned above, I think at least for now I won't use it in this repo. Still, thank you very much for your great work and the discussion.
